mode: "dev" # | "prod"

server:
  port: 5001

ton:
  network: "testnet"
  limit_per_second: 10
  keys:
    testnet:
      - ""
    mainnet:
      - ""
  jetton_transfer_fee: 30000000
  wallet:
    maybe_height: null
    address: ""
    mnemonic: ""
