mode: "dev" # | "prod"

server:
  port: 5001
  swagger:
    title: "Starton API Documentation"
    version: "1.0.0"
  frontend_url: https://quick-hagfish-curious.ngrok-free.app

bot:
  token: ""
  admins: [ 1111111111, 1111111111 ]

logger:
  bot_token: ""
  chat_id: -1111111111111
  dev_thread_id: 2
  prod_thread_id: 4

ton:
  network: "testnet"
  limit_per_second: 10
  keys:
    testnet:
      - ""
    mainnet:
      - ""
  dispenser_wallet_address: ""
