mode: "dev" # | "prod"

server:
  port: 5001
  swagger:
    title: "Starton API Documentation"
    version: "1.0.0"
  frontend_url: https://starton.mom

bot:
  token: ""
  admins: [ 1111111111, 1111111111 ]

ipfs:
  host: "0.0.0.0"
  port: "5001"

ton:
  network: "testnet"
  limit_per_second: 10
  keys:
    testnet:
      - ""
    mainnet:
      - ""
  dispenser_wallet_address: ""
