mode: "dev" # | "prod"

server:
  port: 3001

bot:
  token: "7365089241:AAFaCGvuAUHDIrkiCkOg6foMpjDVmgAY0CU"
  admins: [ 941212988, 483149881 ]

logger:
  bot_token: "7535360860:AAFClh-9FhVd4zgbNKE1pxABvj_xE3EA9DE"
  chat_id: -1002199101106
  dev_thread_id: 2
  prod_thread_id: 4

sale:
  dex_share_pct: 52
  creator_share_pct: 46
