services:
  db:
    image: postgres:latest
    env_file:
      - modules/backend/.env.docker
    volumes:
      - ./modules/backend/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    # We don't need such a verbose build description rn, but later it may be useful
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - modules/backend/.env.docker
    command: sh -c "until pg_isready -h db -p 5432; do echo 'waiting for database...'; sleep 1; done; bun install && bun run modules/backend/src/index.ts"
    depends_on:
      - db
    ports:
      - "3000:3000"
