services:
  db:
    image: postgres:latest
    env_file:
      - .env.docker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  oracle:
    # We don't need such a verbose build description rn, but later it may be useful
    build: .
    working_dir: /app
    volumes:
      - ./oracle:/app
    env_file:
      - .env.docker
    command: sh -c "until pg_isready -h db -p 5432; do echo 'waiting for database...'; sleep 1; done; bun install && bun run modules/oracle/src/index.ts"
    depends_on:
      - db
    ports:
      - "3000:3000"

  manager:
    # We don't need such a verbose build description rn, but later it may be useful
    build: .
    working_dir: /app
    volumes:
      - ./manager:/app
    env_file:
      - .env.docker
    command: sh -c "until pg_isready -h db -p 5432; do echo 'waiting for database...'; sleep 1; done; bun install && bun run modules/manager/src/index.ts"
    depends_on:
      - db
    ports:
      - "3001:3000"
