version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - .env.docker
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  oracle:
    build:
      context: .
      dockerfile: oracle.Dockerfile
    working_dir: /app
    volumes:
      - ./modules/oracle:/app/modules/oracle
      - ./modules/logs[oracle]:/app/modules/logs[oracle]
    env_file:
      - .env.docker
    command: >
      sh -c "until pg_isready -h db -p 5432; do echo 'waiting for database...'; sleep 1; done; 
      bun run migrate.ts && bun run oracle"
    depends_on:
      - db
    ports:
      - "3000:3000"

  manager:
    build:
      context: .
      dockerfile: manager.Dockerfile
    working_dir: /app
    volumes:
      - ./modules/manager:/app/modules/manager
      - ./modules/logs[manager]:/app/modules/logs[manager]
    env_file:
      - .env.docker
    command: >
      sh -c "until pg_isready -h db -p 5432; do echo 'waiting for database...'; sleep 1; done; 
      bun run manager"
    depends_on:
      - db
    ports:
      - "3001:3001"
