# if not - console.debug will not be shown
mode: "dev"
db:
  should_migrate: false

oracle:
  core:
    address: ""
    height: null
    force_height: false
  network: "testnet"
  api_keys:
    testnet_keys:
      - "k"
    mainnet_keys:
      - "k"

server:
  port: 3000
  swagger:
    title: "Starton API Documentation"
    version: "1.0.0"

logger:
  bot_token: ""
  chat_id: -0
  dev_thread_id: 0
  prod_thread_id: 0