# if not - console.debug will not be shown
mode: "dev"

oracle:
  chief:
    address: "",
    mnemonic: ""
  cores:
    - address: ""
      height: null
      force_height: false
      version: "V2A" # "V1"
  network: "testnet"
  api:
    limit_per_second: 10
    keys:
      testnet:
        - "key"
      mainnet:
        - "key"

server:
  port: 3000
  swagger:
    title: "Starton API Documentation"
    version: "1.0.0"

bot:
  token: ""
  admins: [ 1111, 2222 ]

logger:
  bot_token: ""
  chat_id: -0
  dev_thread_id: 0
  prod_thread_id: 0

sale:
  dex_share_pct: 52
  creator_share_pct: 46