mode: "dev" # | "prod"
db:
  should_migrate: true

server:
  port: 5002
  swagger:
    title: "Starton API Documentation"
    version: "1.0.0"
  frontend_url: "https://starton.mom"

oracle:
  chief:
    fallback_vault: ""
    maybe_height:
    address: ""
    mnemonic: ""
  cores:
    - address: ""
      maybe_height: null
      version: "V1"
  network: "testnet"
  api:
    limit_per_second: 10
    keys:
      testnet:
        - "key"
      mainnet:
        - "key"

sale:
  dex_share_pct: 52
  creator_share_pct: 46